# Capstone 2 Results

In [1]:
# I'll only need a few imports here

import pandas as pd
import shap
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
results = pd.read_pickle("results1.pkl")

In [3]:
results.head(10)

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
0,1001001,kNN,codon,dna,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.9981851179673321...",2022-11-29 16:04:12.097193,0 days 00:00:03.480415
1,1001001,kNN,codon,dna,{'k': 2},"{'train_f1': 0.9976989350885642, 'val_f1': 0.9...",2022-11-29 16:04:16.040980,0 days 00:00:03.790893
2,1001001,kNN,codon,dna,{'k': 3},"{'train_f1': 0.9973302007689021, 'val_f1': 0.9...",2022-11-29 16:04:19.848398,0 days 00:00:03.879642
3,1001001,kNN,codon,dna,{'k': 4},"{'train_f1': 0.9962554830426874, 'val_f1': 0.9...",2022-11-29 16:04:23.743797,0 days 00:00:05.662143
4,1001001,kNN,codon,dna,{'k': 5},"{'train_f1': 0.9961554891072192, 'val_f1': 0.9...",2022-11-29 16:04:29.419867,0 days 00:00:05.053719
5,1001001,kNN,codon,dna,{'k': 6},"{'train_f1': 0.9953478423613711, 'val_f1': 0.9...",2022-11-29 16:04:34.490529,0 days 00:00:05.035714
6,1001001,kNN,codon,dna,{'k': 7},"{'train_f1': 0.9949802413756275, 'val_f1': 0.9...",2022-11-29 16:04:39.540178,0 days 00:00:04.914897
7,1001001,kNN,codon,dna,{'k': 8},"{'train_f1': 0.9941189050470489, 'val_f1': 0.9...",2022-11-29 16:04:44.472019,0 days 00:00:05.001064
8,1001001,kNN,codon,dna,{'k': 9},"{'train_f1': 0.9943931222299355, 'val_f1': 0.9...",2022-11-29 16:04:49.489030,0 days 00:00:05.195452
9,1001001,kNN,codon,dna,{'k': 10},"{'train_f1': 0.9936925379516784, 'val_f1': 0.9...",2022-11-29 16:04:54.699443,0 days 00:00:04.942349

In [4]:
results.tail(10)

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
102,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...","{'train_accuracy': 0.995835557928457, 'val_acc...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093
103,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...","{'train_accuracy': 0.9864388681260011, 'val_ac...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628
104,4011001,MLP-SHAP,codon,dna,{'hyperparameters': 'MLP defaults'},"[[[-0.0007548719197966909, 0.00393933436288941...",2022-11-29 18:20:23.092983,0 days 00:03:00.923501
105,4012001,MLP-SHAP,amino,dna,{'hyperparameters': 'MLP defaults'},"[[[-0.05426905473052911, -0.01101713484788619,...",2022-11-29 18:23:24.448165,0 days 00:02:24.666171
106,4013001,MLP-SHAP,codon,king,{'hyperparameters': 'MLP defaults'},"[[[-0.020416657588411095, 0.007916998367115558...",2022-11-29 18:25:49.150125,0 days 00:04:02.380357
107,4014001,MLP-SHAP,amino,king,{'hyperparameters': 'MLP defaults'},"[[[0.0018959274618932267, -0.00791196978596478...",2022-11-29 18:29:51.567339,0 days 00:02:38.899183
108,5001001,GNB,codon,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9113721302722905, 'val_ac...",2022-11-29 18:32:30.591721,0 days 00:00:00.070126
109,5002001,GNB,amino,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9725573945541911, 'val_ac...",2022-11-29 18:32:30.686872,0 days 00:00:00.030608
110,5003001,GNB,codon,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.5681793913507741, 'val_ac...",2022-11-29 18:32:30.752093,0 days 00:00:00.211462
111,5004001,GNB,amino,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.609930592632141, 'val_acc...",2022-11-29 18:32:30.990350,0 days 00:00:00.149825

Let's examine the Shap values that were recorded under 'assessment' for the relevant trials.

In [5]:
shaps = results[results['model_type'].str.contains('SHAP')]

In [6]:
shaps

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
84,2011001,RFC-SHAP,codon,dna,{'n_estimators': 300},"[[[0.00029620426263277046, -0.0006720126358557...",2022-11-29 16:11:02.891357,0 days 00:02:25.054195
85,2012001,RFC-SHAP,amino,dna,{'n_estimators': 300},"[[[0.0012439267939575655, 0.005620548655521513...",2022-11-29 16:13:27.976427,0 days 00:02:48.287982
86,2013001,RFC-SHAP,codon,kingdom,{'n_estimators': 300},"[[[-5.224983653960723e-05, -0.0004761992000260...",2022-11-29 16:16:16.306277,0 days 00:40:58.275176
87,2014001,RFC-SHAP,amino,kingdom,{'n_estimators': 300},"[[[0.0031241616594809784, -0.00045235006564091...",2022-11-29 16:57:14.621323,0 days 00:44:24.513024
92,3011001,XGB-SHAP,codon,dna,{'hyperparameters': 'XGB defaults'},"[[[-0.005294691, 0.034310807, -0.011972199, -0...",2022-11-29 17:41:54.707326,0 days 00:00:02.146811
93,3012001,XGB-SHAP,amino,dna,{'hyperparameters': 'XGB defaults'},"[[[-0.10557593, 0.5746961, 0.057046425, -0.217...",2022-11-29 17:41:56.883874,0 days 00:00:01.928417
94,3013001,XGB-SHAP,codon,king,{'hyperparameters': 'XGB defaults'},"[[[0.013556376, 0.005824473, -0.0036522644, -0...",2022-11-29 17:41:58.837143,0 days 00:00:10.377801
95,3014001,XGB-SHAP,amino,king,{'hyperparameters': 'XGB defaults'},"[[[-0.060978673, -0.009378944, -0.22353487, -0...",2022-11-29 17:42:09.240804,0 days 00:00:08.857937
104,4011001,MLP-SHAP,codon,dna,{'hyperparameters': 'MLP defaults'},"[[[-0.0007548719197966909, 0.00393933436288941...",2022-11-29 18:20:23.092983,0 days 00:03:00.923501
105,4012001,MLP-SHAP,amino,dna,{'hyperparameters': 'MLP defaults'},"[[[-0.05426905473052911, -0.01101713484788619,...",2022-11-29 18:23:24.448165,0 days 00:02:24.666171
106,4013001,MLP-SHAP,codon,king,{'hyperparameters': 'MLP defaults'},"[[[-0.020416657588411095, 0.007916998367115558...",2022-11-29 18:25:49.150125,0 days 00:04:02.380357
107,4014001,MLP-SHAP,amino,king,{'hyperparameters': 'MLP defaults'},"[[[0.0018959274618932267, -0.00791196978596478...",2022-11-29 18:29:51.567339,0 days 00:02:38.899183

It should be simple to produce plots from these Shap values.  In the preceding notebook, I didn't generate any heatmap plots; I'll try now.

In [7]:
shap_values = shaps.at[104, 'assessment']

In [8]:
# ok, maybe this will be less simple than I thought
dir(shap_values)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [9]:
type(shap_values)

list

In [10]:
type(shap_values[0])

numpy.ndarray

In [11]:
shap_values[0]

array([[-0.00075487,  0.00393933,  0.        , ..., -0.00050267,
        -0.01112443, -0.01365095],
       [-0.00168496,  0.00337082, -0.001681  , ...,  0.        ,
         0.        ,  0.        ],
       [-0.00326887,  0.        , -0.00228966, ..., -0.00081436,
        -0.00024096,  0.        ],
       ...,
       [-0.00531738,  0.00385065, -0.00444627, ...,  0.        ,
        -0.00170261,  0.        ],
       [-0.00100154,  0.01930209, -0.02588499, ..., -0.0052822 ,
         0.00575565,  0.00495295],
       [-0.00639191, -0.00198746, -0.00250977, ...,  0.00077852,
         0.00050367, -0.00118632]])

In [12]:
shap_values

[array([[-0.00075487,  0.00393933,  0.        , ..., -0.00050267,
         -0.01112443, -0.01365095],
        [-0.00168496,  0.00337082, -0.001681  , ...,  0.        ,
          0.        ,  0.        ],
        [-0.00326887,  0.        , -0.00228966, ..., -0.00081436,
         -0.00024096,  0.        ],
        ...,
        [-0.00531738,  0.00385065, -0.00444627, ...,  0.        ,
         -0.00170261,  0.        ],
        [-0.00100154,  0.01930209, -0.02588499, ..., -0.0052822 ,
          0.00575565,  0.00495295],
        [-0.00639191, -0.00198746, -0.00250977, ...,  0.00077852,
          0.00050367, -0.00118632]]),
 array([[ 0.02267654, -0.05229811,  0.04160783, ..., -0.00582804,
          0.17402879, -0.39514058],
        [ 0.00429657, -0.00514986,  0.00820408, ...,  0.        ,
         -0.00415127,  0.01371245],
        [ 0.00725039,  0.0025767 ,  0.01045651, ...,  0.        ,
         -0.0047651 ,  0.0115904 ],
        ...,
        [ 0.00661435, -0.00579619,  0.0085585 , ...,  0.00083822,
         -0.00056749,  0.01880526],
        [-0.02293543, -0.06660172, -0.30000845, ...,  0.00651169,
         -0.02050863,  0.01295011],
        [ 0.01006104,  0.00407273,  0.00176822, ..., -0.00394856,
         -0.00407918,  0.01801998]]),
 array([[-0.02241739,  0.04825874, -0.04176112, ...,  0.00614542,
         -0.16302256,  0.40852042],
        [-0.00253777,  0.00176754, -0.00648601, ...,  0.        ,
          0.00349759, -0.01352246],
        [-0.00395468, -0.00261231, -0.00802976, ...,  0.00093358,
          0.00507005, -0.0122713 ],
        ...,
        [-0.00132125,  0.00192776, -0.00405808, ..., -0.00108863,
          0.00228468, -0.01916579],
        [ 0.02403873,  0.04740138,  0.32586367, ...,  0.        ,
          0.01501586, -0.01799153],
        [-0.0036843 , -0.00203252,  0.00077699, ...,  0.00323146,
          0.00351522, -0.01676213]])]

There's obviously going to be a lot more to this than I imagined, and I don't necessarily need any more SHAP plots.

What I do need to do is to assess the 'best' model for each of the four model categories (DNA-codon, DNA-amino, kingdom-codon, kingdom-amino) and overall.

In order to do this, I'm going to need to untangle the assessments column.  Perhaps I should have recorded performance metrics more explicitly to begin with.  Let's start with the kNN models:

In [13]:
knn = results[results['model_type']=='kNN']

In [14]:
knn

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
0,1001001,kNN,codon,dna,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.9981851179673321...",2022-11-29 16:04:12.097193,0 days 00:00:03.480415
1,1001001,kNN,codon,dna,{'k': 2},"{'train_f1': 0.9976989350885642, 'val_f1': 0.9...",2022-11-29 16:04:16.040980,0 days 00:00:03.790893
2,1001001,kNN,codon,dna,{'k': 3},"{'train_f1': 0.9973302007689021, 'val_f1': 0.9...",2022-11-29 16:04:19.848398,0 days 00:00:03.879642
3,1001001,kNN,codon,dna,{'k': 4},"{'train_f1': 0.9962554830426874, 'val_f1': 0.9...",2022-11-29 16:04:23.743797,0 days 00:00:05.662143
4,1001001,kNN,codon,dna,{'k': 5},"{'train_f1': 0.9961554891072192, 'val_f1': 0.9...",2022-11-29 16:04:29.419867,0 days 00:00:05.053719
5,1001001,kNN,codon,dna,{'k': 6},"{'train_f1': 0.9953478423613711, 'val_f1': 0.9...",2022-11-29 16:04:34.490529,0 days 00:00:05.035714
6,1001001,kNN,codon,dna,{'k': 7},"{'train_f1': 0.9949802413756275, 'val_f1': 0.9...",2022-11-29 16:04:39.540178,0 days 00:00:04.914897
7,1001001,kNN,codon,dna,{'k': 8},"{'train_f1': 0.9941189050470489, 'val_f1': 0.9...",2022-11-29 16:04:44.472019,0 days 00:00:05.001064
8,1001001,kNN,codon,dna,{'k': 9},"{'train_f1': 0.9943931222299355, 'val_f1': 0.9...",2022-11-29 16:04:49.489030,0 days 00:00:05.195452
9,1001001,kNN,codon,dna,{'k': 10},"{'train_f1': 0.9936925379516784, 'val_f1': 0.9...",2022-11-29 16:04:54.699443,0 days 00:00:04.942349
10,1002001,kNN,amino,dna,{'k': 1},"{'train_f1': 0.999893219434063, 'val_f1': 0.99...",2022-11-29 16:04:59.951773,0 days 00:00:03.408583
11,1002001,kNN,amino,dna,{'k': 2},"{'train_f1': 0.9961410654946938, 'val_f1': 0.9...",2022-11-29 16:05:03.377287,0 days 00:00:03.726181
12,1002001,kNN,amino,dna,{'k': 3},"{'train_f1': 0.9954610989480429, 'val_f1': 0.9...",2022-11-29 16:05:07.119415,0 days 00:00:03.754226
13,1002001,kNN,amino,dna,{'k': 4},"{'train_f1': 0.9941138698630139, 'val_f1': 0.9...",2022-11-29 16:05:10.893240,0 days 00:00:04.967967
14,1002001,kNN,amino,dna,{'k': 5},"{'train_f1': 0.9940727292145031, 'val_f1': 0.9...",2022-11-29 16:05:15.875163,0 days 00:00:04.961172
15,1002001,kNN,amino,dna,{'k': 6},"{'train_f1': 0.9933696930809538, 'val_f1': 0.9...",2022-11-29 16:05:20.850281,0 days 00:00:05.126645
16,1002001,kNN,amino,dna,{'k': 7},"{'train_f1': 0.9931638538773766, 'val_f1': 0.9...",2022-11-29 16:05:25.991876,0 days 00:00:04.901008
17,1002001,kNN,amino,dna,{'k': 8},"{'train_f1': 0.9924064171122995, 'val_f1': 0.9...",2022-11-29 16:05:30.906832,0 days 00:00:04.999632
18,1002001,kNN,amino,dna,{'k': 9},"{'train_f1': 0.9924145299145299, 'val_f1': 0.9...",2022-11-29 16:05:35.920461,0 days 00:00:05.126452
19,1002001,kNN,amino,dna,{'k': 10},"{'train_f1': 0.9919794674366379, 'val_f1': 0.9...",2022-11-29 16:05:41.061918,0 days 00:00:04.965723
20,1003001,kNN,codon,king,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.9364791288566244...",2022-11-29 16:05:46.350600,0 days 00:00:04.571322
21,1003001,kNN,codon,king,{'k': 2},"{'train_f1': 0.9646785694544249, 'val_f1': 0.9...",2022-11-29 16:05:50.939862,0 days 00:00:04.884619
22,1003001,kNN,codon,king,{'k': 3},"{'train_f1': 0.9631779820459064, 'val_f1': 0.9...",2022-11-29 16:05:55.838435,0 days 00:00:05.072418
23,1003001,kNN,codon,king,{'k': 4},"{'train_f1': 0.9491301475445937, 'val_f1': 0.9...",2022-11-29 16:06:00.927794,0 days 00:00:06.315783
24,1003001,kNN,codon,king,{'k': 5},"{'train_f1': 0.9473456823459524, 'val_f1': 0.9...",2022-11-29 16:06:07.257531,0 days 00:00:06.370517
25,1003001,kNN,codon,king,{'k': 6},"{'train_f1': 0.9357352047300657, 'val_f1': 0.9...",2022-11-29 16:06:13.648950,0 days 00:00:06.140514
26,1003001,kNN,codon,king,{'k': 7},"{'train_f1': 0.9344395640149666, 'val_f1': 0.9...",2022-11-29 16:06:19.803424,0 days 00:00:06.357024
27,1003001,kNN,codon,king,{'k': 8},"{'train_f1': 0.9265330904675168, 'val_f1': 0.8...",2022-11-29 16:06:26.177389,0 days 00:00:06.287282
28,1003001,kNN,codon,king,{'k': 9},"{'train_f1': 0.9258977149075082, 'val_f1': 0.9...",2022-11-29 16:06:32.479631,0 days 00:00:06.190054
29,1003001,kNN,codon,king,{'k': 10},"{'train_f1': 0.9174088620899484, 'val_f1': 0.8...",2022-11-29 16:06:38.684656,0 days 00:00:06.374559
30,1004001,kNN,amino,king,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.8517846339987901...",2022-11-29 16:06:45.454885,0 days 00:00:04.478091
31,1004001,kNN,amino,king,{'k': 2},"{'train_f1': 0.9273237500715882, 'val_f1': 0.8...",2022-11-29 16:06:49.950987,0 days 00:00:04.797070
32,1004001,kNN,amino,king,{'k': 3},"{'train_f1': 0.9279695569448221, 'val_f1': 0.8...",2022-11-29 16:06:54.762894,0 days 00:00:05.091228
33,1004001,kNN,amino,king,{'k': 4},"{'train_f1': 0.9020031868882312, 'val_f1': 0.8...",2022-11-29 16:06:59.873091,0 days 00:00:06.155514
34,1004001,kNN,amino,king,{'k': 5},"{'train_f1': 0.9021243893066916, 'val_f1': 0.8...",2022-11-29 16:07:06.042562,0 days 00:00:06.094747
35,1004001,kNN,amino,king,{'k': 6},"{'train_f1': 0.8859938559563091, 'val_f1': 0.8...",2022-11-29 16:07:12.151261,0 days 00:00:06.293300
36,1004001,kNN,amino,king,{'k': 7},"{'train_f1': 0.8887289636846767, 'val_f1': 0.8...",2022-11-29 16:07:18.458515,0 days 00:00:06.107298
37,1004001,kNN,amino,king,{'k': 8},"{'train_f1': 0.8742644958583263, 'val_f1': 0.8...",2022-11-29 16:07:24.579766,0 days 00:00:06.307260
38,1004001,kNN,amino,king,{'k': 9},"{'train_f1': 0.8747976555958693, 'val_f1': 0.8...",2022-11-29 16:07:30.900966,0 days 00:00:06.136711
39,1004001,kNN,amino,king,{'k': 10},"{'train_f1': 0.8644814369887307, 'val_f1': 0.8...",2022-11-29 16:07:37.051634,0 days 00:00:06.142360

In [15]:
exploring = knn.assessment[0]

In [16]:
exploring

{'train_f1': 1.0,
 'val_f1': 0.9981851179673321,
 'test_f1': 0.9928020565552699,
 'train_accuracy': 1.0,
 'val_accuracy': 0.9981851179673321,
 'test_accuracy': 0.9928020565552699,
 'train_roc_auc': 0.9917948477709857,
 'val_roc_auc': 0.9990284974093264,
 'test_roc_auc': 0.9917948477709857}

In [17]:
# this feels stupid, but, hey, practice:
# make a function to take an arbitrary dataframe, examine the contents of a column named 'assessment'
# it should contain dicts.  Read the dict, create a new column-value for each key-value pair in the dict

def expand_assessment(df):
    assessment = df.assessment
    new_df = pd.DataFrame(columns = assessment[0].keys())
    for assx in assessment:
        new_df = new_df.append(assx, ignore_index=True)
    return new_df

In [18]:
test1 = expand_assessment(knn)

In [19]:
test1[:5]

,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
1,0.997699,0.996968,0.991224,0.995408,0.994555,0.987147,0.99034,0.997256,0.99034
2,0.99733,0.997579,0.990741,0.997224,0.996975,0.990231,0.990398,0.996975,0.990398
3,0.996255,0.996668,0.990206,0.994341,0.99516,0.987661,0.990447,0.996067,0.990447
4,0.996155,0.996368,0.990481,0.996049,0.995765,0.989717,0.990194,0.994878,0.990194

In [20]:
test1[test1.test_f1 == test1.test_accuracy.max()]

,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795

In [21]:
test1.shape

(40, 9)

ok, this checks out... need to apply it a little better... insert these columns within the original results dataframe?  Break it up for each of the four cases?

In [22]:
results[40:100]

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
40,2001001,RFC,codon,dna,{'n_estimators': 200},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.224953
41,2001001,RFC,codon,dna,{'n_estimators': 220},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.239903
42,2001001,RFC,codon,dna,{'n_estimators': 240},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.250867
43,2001001,RFC,codon,dna,{'n_estimators': 260},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.261830
44,2001001,RFC,codon,dna,{'n_estimators': 280},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.273790
45,2001001,RFC,codon,dna,{'n_estimators': 300},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.284754
46,2001001,RFC,codon,dna,{'n_estimators': 320},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.295717
47,2001001,RFC,codon,dna,{'n_estimators': 340},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.306680
48,2001001,RFC,codon,dna,{'n_estimators': 360},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.318640
49,2001001,RFC,codon,dna,{'n_estimators': 380},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.329604
50,2001001,RFC,codon,dna,{'n_estimators': 400},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.340567
51,2002001,RFC,amino,dna,{'n_estimators': 200},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.824370
52,2002001,RFC,amino,dna,{'n_estimators': 220},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.838326
53,2002001,RFC,amino,dna,{'n_estimators': 240},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.851319
54,2002001,RFC,amino,dna,{'n_estimators': 260},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.863242
55,2002001,RFC,amino,dna,{'n_estimators': 280},"{'train_f1': 1.0, 'val_f1': 0.9875719915125796...",2022-11-29 16:08:46.856963,0 days 00:00:02.875197
56,2002001,RFC,amino,dna,{'n_estimators': 300},"{'train_f1': 1.0, 'val_f1': 0.9872727272727274...",2022-11-29 16:08:46.856963,0 days 00:00:02.887154
57,2002001,RFC,amino,dna,{'n_estimators': 320},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.900102
58,2002001,RFC,amino,dna,{'n_estimators': 340},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.911078
59,2002001,RFC,amino,dna,{'n_estimators': 360},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.925031
60,2002001,RFC,amino,dna,{'n_estimators': 380},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.938004
61,2002001,RFC,amino,dna,{'n_estimators': 400},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.949945
62,2003001,RFC,codon,kingdom,{'n_estimators': 200},"{'train_f1': 1.0, 'val_f1': 0.8509041282838622...",2022-11-29 16:09:54.119362,0 days 00:00:08.705608
63,2003001,RFC,codon,kingdom,{'n_estimators': 220},"{'train_f1': 1.0, 'val_f1': 0.849539406345957,...",2022-11-29 16:09:54.119362,0 days 00:00:08.719576
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},"{'train_f1': 1.0, 'val_f1': 0.8484641638225255...",2022-11-29 16:09:54.119362,0 days 00:00:08.730520
65,2003001,RFC,codon,kingdom,{'n_estimators': 260},"{'train_f1': 1.0, 'val_f1': 0.8489601091033072...",2022-11-29 16:09:54.119362,0 days 00:00:08.742486
66,2003001,RFC,codon,kingdom,{'n_estimators': 280},"{'train_f1': 1.0, 'val_f1': 0.8498293515358363...",2022-11-29 16:09:54.119362,0 days 00:00:08.753403
67,2003001,RFC,codon,kingdom,{'n_estimators': 300},"{'train_f1': 1.0, 'val_f1': 0.8517887563884157...",2022-11-29 16:09:54.119362,0 days 00:00:08.765407
68,2003001,RFC,codon,kingdom,{'n_estimators': 320},"{'train_f1': 1.0, 'val_f1': 0.849931787175989,...",2022-11-29 16:09:54.119362,0 days 00:00:08.776372
69,2003001,RFC,codon,kingdom,{'n_estimators': 340},"{'train_f1': 1.0, 'val_f1': 0.8528610354223434...",2022-11-29 16:09:54.119362,0 days 00:00:08.787339
70,2003001,RFC,codon,kingdom,{'n_estimators': 360},"{'train_f1': 1.0, 'val_f1': 0.8534512070724243...",2022-11-29 16:09:54.119362,0 days 00:00:08.799298
71,2003001,RFC,codon,kingdom,{'n_estimators': 380},"{'train_f1': 1.0, 'val_f1': 0.8530612244897959...",2022-11-29 16:09:54.119362,0 days 00:00:08.810258
72,2003001,RFC,codon,kingdom,{'n_estimators': 400},"{'train_f1': 1.0, 'val_f1': 0.8524813052345342...",2022-11-29 16:09:54.119362,0 days 00:00:08.821226
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},"{'train_f1': 1.0, 'val_f1': 0.8205841446453407...",2022-11-29 16:10:55.333264,0 days 00:00:07.051315
74,2004001,RFC,amino,kingdom,{'n_estimators': 220},"{'train_f1': 1.0, 'val_f1': 0.823202500868357,...",2022-11-29 16:10:55.333264,0 days 00:00:07.068262
75,2004001,RFC,amino,kingdom,{'n_estimators': 240},"{'train_f1': 1.0, 'val_f1': 0.8219749652294853...",2022-11-29 16:10:55.333264,0 days 00:00:07.079240
76,2004001,RFC,amino,kingdom,{'n_estimators': 260},"{'train_f1': 1.0, 'val_f1': 0.8202090592334494...",2022-11-29 16:10:55.333264,0 days 00:00:07.090195
77,2004001,RFC,amino,kingdom,{'n_estimators': 280},"{'train_f1': 1.0, 'val_f1': 0.8203342618384402...",2022-11-29 16:10:55.333264,0 days 00:00:07.102154
78,2004001,RFC,amino,kingdom,{'n_estimators': 300},"{'train_f1': 1.0, 'val_f1': 0.8222608695652174...",2022-11-29 16:10:55.333264,0 days 00:00:07.112124
79,2004001,RFC,amino,kingdom,{'n_estimators': 320},"{'train_f1': 1.0, 'val_f1': 0.8218510786360473...",2022-11-29 16:10:55.333264,0 days 00:00:07.124080
80,2004001,RFC,amino,kingdom,{'n_estimators': 340},"{'train_f1': 1.0, 'val_f1': 0.820494945974207,...",2022-11-29 16:10:55.333264,0 days 00:00:07.134053
81,2004001,RFC,amino,kingdom,{'n_estimators': 360},"{'train_f1': 1.0, 'val_f1': 0.820494945974207,...",2022-11-29 16:10:55.333264,0 days 00:00:07.146007
82,2004001,RFC,amino,kingdom,{'n_estimators': 380},"{'train_f1': 1.0, 'val_f1': 0.8218891599860578...",2022-11-29 16:10:55.333264,0 days 00:00:07.156927
83,2004001,RFC,amino,kingdom,{'n_estimators': 400},"{'train_f1': 1.0, 'val_f1': 0.820494945974207,...",2022-11-29 16:10:55.333264,0 days 00:00:07.167932
84,2011001,RFC-SHAP,codon,dna,{'n_estimators': 300},"[[[0.00029620426263277046, -0.0006720126358557...",2022-11-29 16:11:02.891357,0 days 00:02:25.054195
85,2012001,RFC-SHAP,amino,dna,{'n_estimators': 300},"[[[0.0012439267939575655, 0.005620548655521513...",2022-11-29 16:13:27.976427,0 days 00:02:48.287982
86,2013001,RFC-SHAP,codon,kingdom,{'n_estimators': 300},"[[[-5.224983653960723e-05, -0.0004761992000260...",2022-11-29 16:16:16.306277,0 days 00:40:58.275176
87,2014001,RFC-SHAP,amino,kingdom,{'n_estimators': 300},"[[[0.0031241616594809784, -0.00045235006564091...",2022-11-29 16:57:14.621323,0 days 00:44:24.513024
88,3001001,XGB,codon,dna,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 0.999893219434063, 'val_acc...",2022-11-29 17:41:41.378498,0 days 00:00:01.378242
89,3002001,XGB,amino,dna,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 1.0, 'val_accuracy': 0.9915...",2022-11-29 17:41:42.784433,0 days 00:00:00.846796
90,3003001,XGB,codon,kingdom,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 1.0, 'val_accuracy': 0.9219...",2022-11-29 17:41:43.665968,0 days 00:00:06.712829
91,3004001,XGB,amino,kingdom,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 1.0, 'val_accuracy': 0.8644...",2022-11-29 17:41:50.400644,0 days 00:00:04.256763
92,3011001,XGB-SHAP,codon,dna,{'hyperparameters': 'XGB defaults'},"[[[-0.005294691, 0.034310807, -0.011972199, -0...",2022-11-29 17:41:54.707326,0 days 00:00:02.146811
93,3012001,XGB-SHAP,amino,dna,{'hyperparameters': 'XGB defaults'},"[[[-0.10557593, 0.5746961, 0.057046425, -0.217...",2022-11-29 17:41:56.883874,0 days 00:00:01.928417
94,3013001,XGB-SHAP,codon,king,{'hyperparameters': 'XGB defaults'},"[[[0.013556376, 0.005824473, -0.0036522644, -0...",2022-11-29 17:41:58.837143,0 days 00:00:10.377801
95,3014001,XGB-SHAP,amino,king,{'hyperparameters': 'XGB defaults'},"[[[-0.060978673, -0.009378944, -0.22353487, -0...",2022-11-29 17:42:09.240804,0 days 00:00:08.857937
96,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...","{'train_accuracy': 0.9817405232247731, 'val_ac...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798
97,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...","{'train_accuracy': 0.9750133475707421, 'val_ac...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893
98,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...","{'train_accuracy': 0.7753336892685532, 'val_ac...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428
99,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...","{'train_accuracy': 0.7326214628937533, 'val_ac...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763

It could be easier just to remove everything that doesn't have a dictionary with the same keys in the 'assessment' column.  That really would be the just the 'SHAP' results, where 'assessment' stores the SHAP values.

In [24]:
results.shape

(112, 8)

In [25]:
shaps = results[results['model_type'].str.contains('SHAP')]
shaps.shape

(12, 8)

In [26]:
shaps

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
84,2011001,RFC-SHAP,codon,dna,{'n_estimators': 300},"[[[0.00029620426263277046, -0.0006720126358557...",2022-11-29 16:11:02.891357,0 days 00:02:25.054195
85,2012001,RFC-SHAP,amino,dna,{'n_estimators': 300},"[[[0.0012439267939575655, 0.005620548655521513...",2022-11-29 16:13:27.976427,0 days 00:02:48.287982
86,2013001,RFC-SHAP,codon,kingdom,{'n_estimators': 300},"[[[-5.224983653960723e-05, -0.0004761992000260...",2022-11-29 16:16:16.306277,0 days 00:40:58.275176
87,2014001,RFC-SHAP,amino,kingdom,{'n_estimators': 300},"[[[0.0031241616594809784, -0.00045235006564091...",2022-11-29 16:57:14.621323,0 days 00:44:24.513024
92,3011001,XGB-SHAP,codon,dna,{'hyperparameters': 'XGB defaults'},"[[[-0.005294691, 0.034310807, -0.011972199, -0...",2022-11-29 17:41:54.707326,0 days 00:00:02.146811
93,3012001,XGB-SHAP,amino,dna,{'hyperparameters': 'XGB defaults'},"[[[-0.10557593, 0.5746961, 0.057046425, -0.217...",2022-11-29 17:41:56.883874,0 days 00:00:01.928417
94,3013001,XGB-SHAP,codon,king,{'hyperparameters': 'XGB defaults'},"[[[0.013556376, 0.005824473, -0.0036522644, -0...",2022-11-29 17:41:58.837143,0 days 00:00:10.377801
95,3014001,XGB-SHAP,amino,king,{'hyperparameters': 'XGB defaults'},"[[[-0.060978673, -0.009378944, -0.22353487, -0...",2022-11-29 17:42:09.240804,0 days 00:00:08.857937
104,4011001,MLP-SHAP,codon,dna,{'hyperparameters': 'MLP defaults'},"[[[-0.0007548719197966909, 0.00393933436288941...",2022-11-29 18:20:23.092983,0 days 00:03:00.923501
105,4012001,MLP-SHAP,amino,dna,{'hyperparameters': 'MLP defaults'},"[[[-0.05426905473052911, -0.01101713484788619,...",2022-11-29 18:23:24.448165,0 days 00:02:24.666171
106,4013001,MLP-SHAP,codon,king,{'hyperparameters': 'MLP defaults'},"[[[-0.020416657588411095, 0.007916998367115558...",2022-11-29 18:25:49.150125,0 days 00:04:02.380357
107,4014001,MLP-SHAP,amino,king,{'hyperparameters': 'MLP defaults'},"[[[0.0018959274618932267, -0.00791196978596478...",2022-11-29 18:29:51.567339,0 days 00:02:38.899183

In [27]:
results = results[~results["model_type"].str.contains("SHAP")]

In [28]:
results.shape

(100, 8)

As it should be.

In [29]:
results[:20]

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
0,1001001,kNN,codon,dna,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.9981851179673321...",2022-11-29 16:04:12.097193,0 days 00:00:03.480415
1,1001001,kNN,codon,dna,{'k': 2},"{'train_f1': 0.9976989350885642, 'val_f1': 0.9...",2022-11-29 16:04:16.040980,0 days 00:00:03.790893
2,1001001,kNN,codon,dna,{'k': 3},"{'train_f1': 0.9973302007689021, 'val_f1': 0.9...",2022-11-29 16:04:19.848398,0 days 00:00:03.879642
3,1001001,kNN,codon,dna,{'k': 4},"{'train_f1': 0.9962554830426874, 'val_f1': 0.9...",2022-11-29 16:04:23.743797,0 days 00:00:05.662143
4,1001001,kNN,codon,dna,{'k': 5},"{'train_f1': 0.9961554891072192, 'val_f1': 0.9...",2022-11-29 16:04:29.419867,0 days 00:00:05.053719
5,1001001,kNN,codon,dna,{'k': 6},"{'train_f1': 0.9953478423613711, 'val_f1': 0.9...",2022-11-29 16:04:34.490529,0 days 00:00:05.035714
6,1001001,kNN,codon,dna,{'k': 7},"{'train_f1': 0.9949802413756275, 'val_f1': 0.9...",2022-11-29 16:04:39.540178,0 days 00:00:04.914897
7,1001001,kNN,codon,dna,{'k': 8},"{'train_f1': 0.9941189050470489, 'val_f1': 0.9...",2022-11-29 16:04:44.472019,0 days 00:00:05.001064
8,1001001,kNN,codon,dna,{'k': 9},"{'train_f1': 0.9943931222299355, 'val_f1': 0.9...",2022-11-29 16:04:49.489030,0 days 00:00:05.195452
9,1001001,kNN,codon,dna,{'k': 10},"{'train_f1': 0.9936925379516784, 'val_f1': 0.9...",2022-11-29 16:04:54.699443,0 days 00:00:04.942349
10,1002001,kNN,amino,dna,{'k': 1},"{'train_f1': 0.999893219434063, 'val_f1': 0.99...",2022-11-29 16:04:59.951773,0 days 00:00:03.408583
11,1002001,kNN,amino,dna,{'k': 2},"{'train_f1': 0.9961410654946938, 'val_f1': 0.9...",2022-11-29 16:05:03.377287,0 days 00:00:03.726181
12,1002001,kNN,amino,dna,{'k': 3},"{'train_f1': 0.9954610989480429, 'val_f1': 0.9...",2022-11-29 16:05:07.119415,0 days 00:00:03.754226
13,1002001,kNN,amino,dna,{'k': 4},"{'train_f1': 0.9941138698630139, 'val_f1': 0.9...",2022-11-29 16:05:10.893240,0 days 00:00:04.967967
14,1002001,kNN,amino,dna,{'k': 5},"{'train_f1': 0.9940727292145031, 'val_f1': 0.9...",2022-11-29 16:05:15.875163,0 days 00:00:04.961172
15,1002001,kNN,amino,dna,{'k': 6},"{'train_f1': 0.9933696930809538, 'val_f1': 0.9...",2022-11-29 16:05:20.850281,0 days 00:00:05.126645
16,1002001,kNN,amino,dna,{'k': 7},"{'train_f1': 0.9931638538773766, 'val_f1': 0.9...",2022-11-29 16:05:25.991876,0 days 00:00:04.901008
17,1002001,kNN,amino,dna,{'k': 8},"{'train_f1': 0.9924064171122995, 'val_f1': 0.9...",2022-11-29 16:05:30.906832,0 days 00:00:04.999632
18,1002001,kNN,amino,dna,{'k': 9},"{'train_f1': 0.9924145299145299, 'val_f1': 0.9...",2022-11-29 16:05:35.920461,0 days 00:00:05.126452
19,1002001,kNN,amino,dna,{'k': 10},"{'train_f1': 0.9919794674366379, 'val_f1': 0.9...",2022-11-29 16:05:41.061918,0 days 00:00:04.965723

In [30]:
results[20:40]

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
20,1003001,kNN,codon,king,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.9364791288566244...",2022-11-29 16:05:46.350600,0 days 00:00:04.571322
21,1003001,kNN,codon,king,{'k': 2},"{'train_f1': 0.9646785694544249, 'val_f1': 0.9...",2022-11-29 16:05:50.939862,0 days 00:00:04.884619
22,1003001,kNN,codon,king,{'k': 3},"{'train_f1': 0.9631779820459064, 'val_f1': 0.9...",2022-11-29 16:05:55.838435,0 days 00:00:05.072418
23,1003001,kNN,codon,king,{'k': 4},"{'train_f1': 0.9491301475445937, 'val_f1': 0.9...",2022-11-29 16:06:00.927794,0 days 00:00:06.315783
24,1003001,kNN,codon,king,{'k': 5},"{'train_f1': 0.9473456823459524, 'val_f1': 0.9...",2022-11-29 16:06:07.257531,0 days 00:00:06.370517
25,1003001,kNN,codon,king,{'k': 6},"{'train_f1': 0.9357352047300657, 'val_f1': 0.9...",2022-11-29 16:06:13.648950,0 days 00:00:06.140514
26,1003001,kNN,codon,king,{'k': 7},"{'train_f1': 0.9344395640149666, 'val_f1': 0.9...",2022-11-29 16:06:19.803424,0 days 00:00:06.357024
27,1003001,kNN,codon,king,{'k': 8},"{'train_f1': 0.9265330904675168, 'val_f1': 0.8...",2022-11-29 16:06:26.177389,0 days 00:00:06.287282
28,1003001,kNN,codon,king,{'k': 9},"{'train_f1': 0.9258977149075082, 'val_f1': 0.9...",2022-11-29 16:06:32.479631,0 days 00:00:06.190054
29,1003001,kNN,codon,king,{'k': 10},"{'train_f1': 0.9174088620899484, 'val_f1': 0.8...",2022-11-29 16:06:38.684656,0 days 00:00:06.374559
30,1004001,kNN,amino,king,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.8517846339987901...",2022-11-29 16:06:45.454885,0 days 00:00:04.478091
31,1004001,kNN,amino,king,{'k': 2},"{'train_f1': 0.9273237500715882, 'val_f1': 0.8...",2022-11-29 16:06:49.950987,0 days 00:00:04.797070
32,1004001,kNN,amino,king,{'k': 3},"{'train_f1': 0.9279695569448221, 'val_f1': 0.8...",2022-11-29 16:06:54.762894,0 days 00:00:05.091228
33,1004001,kNN,amino,king,{'k': 4},"{'train_f1': 0.9020031868882312, 'val_f1': 0.8...",2022-11-29 16:06:59.873091,0 days 00:00:06.155514
34,1004001,kNN,amino,king,{'k': 5},"{'train_f1': 0.9021243893066916, 'val_f1': 0.8...",2022-11-29 16:07:06.042562,0 days 00:00:06.094747
35,1004001,kNN,amino,king,{'k': 6},"{'train_f1': 0.8859938559563091, 'val_f1': 0.8...",2022-11-29 16:07:12.151261,0 days 00:00:06.293300
36,1004001,kNN,amino,king,{'k': 7},"{'train_f1': 0.8887289636846767, 'val_f1': 0.8...",2022-11-29 16:07:18.458515,0 days 00:00:06.107298
37,1004001,kNN,amino,king,{'k': 8},"{'train_f1': 0.8742644958583263, 'val_f1': 0.8...",2022-11-29 16:07:24.579766,0 days 00:00:06.307260
38,1004001,kNN,amino,king,{'k': 9},"{'train_f1': 0.8747976555958693, 'val_f1': 0.8...",2022-11-29 16:07:30.900966,0 days 00:00:06.136711
39,1004001,kNN,amino,king,{'k': 10},"{'train_f1': 0.8644814369887307, 'val_f1': 0.8...",2022-11-29 16:07:37.051634,0 days 00:00:06.142360

In [31]:
results[40:60]

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
40,2001001,RFC,codon,dna,{'n_estimators': 200},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.224953
41,2001001,RFC,codon,dna,{'n_estimators': 220},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.239903
42,2001001,RFC,codon,dna,{'n_estimators': 240},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.250867
43,2001001,RFC,codon,dna,{'n_estimators': 260},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.261830
44,2001001,RFC,codon,dna,{'n_estimators': 280},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.273790
45,2001001,RFC,codon,dna,{'n_estimators': 300},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.284754
46,2001001,RFC,codon,dna,{'n_estimators': 320},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.295717
47,2001001,RFC,codon,dna,{'n_estimators': 340},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.306680
48,2001001,RFC,codon,dna,{'n_estimators': 360},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.318640
49,2001001,RFC,codon,dna,{'n_estimators': 380},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.329604
50,2001001,RFC,codon,dna,{'n_estimators': 400},"{'train_f1': 0.999893219434063, 'val_f1': 0.98...",2022-11-29 16:08:24.053694,0 days 00:00:03.340567
51,2002001,RFC,amino,dna,{'n_estimators': 200},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.824370
52,2002001,RFC,amino,dna,{'n_estimators': 220},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.838326
53,2002001,RFC,amino,dna,{'n_estimators': 240},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.851319
54,2002001,RFC,amino,dna,{'n_estimators': 260},"{'train_f1': 1.0, 'val_f1': 0.9875795213571644...",2022-11-29 16:08:46.856963,0 days 00:00:02.863242
55,2002001,RFC,amino,dna,{'n_estimators': 280},"{'train_f1': 1.0, 'val_f1': 0.9875719915125796...",2022-11-29 16:08:46.856963,0 days 00:00:02.875197
56,2002001,RFC,amino,dna,{'n_estimators': 300},"{'train_f1': 1.0, 'val_f1': 0.9872727272727274...",2022-11-29 16:08:46.856963,0 days 00:00:02.887154
57,2002001,RFC,amino,dna,{'n_estimators': 320},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.900102
58,2002001,RFC,amino,dna,{'n_estimators': 340},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.911078
59,2002001,RFC,amino,dna,{'n_estimators': 360},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.925031

In [32]:
results[60:80]

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
60,2002001,RFC,amino,dna,{'n_estimators': 380},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.938004
61,2002001,RFC,amino,dna,{'n_estimators': 400},"{'train_f1': 1.0, 'val_f1': 0.9866666666666667...",2022-11-29 16:08:46.856963,0 days 00:00:02.949945
62,2003001,RFC,codon,kingdom,{'n_estimators': 200},"{'train_f1': 1.0, 'val_f1': 0.8509041282838622...",2022-11-29 16:09:54.119362,0 days 00:00:08.705608
63,2003001,RFC,codon,kingdom,{'n_estimators': 220},"{'train_f1': 1.0, 'val_f1': 0.849539406345957,...",2022-11-29 16:09:54.119362,0 days 00:00:08.719576
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},"{'train_f1': 1.0, 'val_f1': 0.8484641638225255...",2022-11-29 16:09:54.119362,0 days 00:00:08.730520
65,2003001,RFC,codon,kingdom,{'n_estimators': 260},"{'train_f1': 1.0, 'val_f1': 0.8489601091033072...",2022-11-29 16:09:54.119362,0 days 00:00:08.742486
66,2003001,RFC,codon,kingdom,{'n_estimators': 280},"{'train_f1': 1.0, 'val_f1': 0.8498293515358363...",2022-11-29 16:09:54.119362,0 days 00:00:08.753403
67,2003001,RFC,codon,kingdom,{'n_estimators': 300},"{'train_f1': 1.0, 'val_f1': 0.8517887563884157...",2022-11-29 16:09:54.119362,0 days 00:00:08.765407
68,2003001,RFC,codon,kingdom,{'n_estimators': 320},"{'train_f1': 1.0, 'val_f1': 0.849931787175989,...",2022-11-29 16:09:54.119362,0 days 00:00:08.776372
69,2003001,RFC,codon,kingdom,{'n_estimators': 340},"{'train_f1': 1.0, 'val_f1': 0.8528610354223434...",2022-11-29 16:09:54.119362,0 days 00:00:08.787339
70,2003001,RFC,codon,kingdom,{'n_estimators': 360},"{'train_f1': 1.0, 'val_f1': 0.8534512070724243...",2022-11-29 16:09:54.119362,0 days 00:00:08.799298
71,2003001,RFC,codon,kingdom,{'n_estimators': 380},"{'train_f1': 1.0, 'val_f1': 0.8530612244897959...",2022-11-29 16:09:54.119362,0 days 00:00:08.810258
72,2003001,RFC,codon,kingdom,{'n_estimators': 400},"{'train_f1': 1.0, 'val_f1': 0.8524813052345342...",2022-11-29 16:09:54.119362,0 days 00:00:08.821226
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},"{'train_f1': 1.0, 'val_f1': 0.8205841446453407...",2022-11-29 16:10:55.333264,0 days 00:00:07.051315
74,2004001,RFC,amino,kingdom,{'n_estimators': 220},"{'train_f1': 1.0, 'val_f1': 0.823202500868357,...",2022-11-29 16:10:55.333264,0 days 00:00:07.068262
75,2004001,RFC,amino,kingdom,{'n_estimators': 240},"{'train_f1': 1.0, 'val_f1': 0.8219749652294853...",2022-11-29 16:10:55.333264,0 days 00:00:07.079240
76,2004001,RFC,amino,kingdom,{'n_estimators': 260},"{'train_f1': 1.0, 'val_f1': 0.8202090592334494...",2022-11-29 16:10:55.333264,0 days 00:00:07.090195
77,2004001,RFC,amino,kingdom,{'n_estimators': 280},"{'train_f1': 1.0, 'val_f1': 0.8203342618384402...",2022-11-29 16:10:55.333264,0 days 00:00:07.102154
78,2004001,RFC,amino,kingdom,{'n_estimators': 300},"{'train_f1': 1.0, 'val_f1': 0.8222608695652174...",2022-11-29 16:10:55.333264,0 days 00:00:07.112124
79,2004001,RFC,amino,kingdom,{'n_estimators': 320},"{'train_f1': 1.0, 'val_f1': 0.8218510786360473...",2022-11-29 16:10:55.333264,0 days 00:00:07.124080

In [33]:
results[80:100]

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
80,2004001,RFC,amino,kingdom,{'n_estimators': 340},"{'train_f1': 1.0, 'val_f1': 0.820494945974207,...",2022-11-29 16:10:55.333264,0 days 00:00:07.134053
81,2004001,RFC,amino,kingdom,{'n_estimators': 360},"{'train_f1': 1.0, 'val_f1': 0.820494945974207,...",2022-11-29 16:10:55.333264,0 days 00:00:07.146007
82,2004001,RFC,amino,kingdom,{'n_estimators': 380},"{'train_f1': 1.0, 'val_f1': 0.8218891599860578...",2022-11-29 16:10:55.333264,0 days 00:00:07.156927
83,2004001,RFC,amino,kingdom,{'n_estimators': 400},"{'train_f1': 1.0, 'val_f1': 0.820494945974207,...",2022-11-29 16:10:55.333264,0 days 00:00:07.167932
88,3001001,XGB,codon,dna,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 0.999893219434063, 'val_acc...",2022-11-29 17:41:41.378498,0 days 00:00:01.378242
89,3002001,XGB,amino,dna,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 1.0, 'val_accuracy': 0.9915...",2022-11-29 17:41:42.784433,0 days 00:00:00.846796
90,3003001,XGB,codon,kingdom,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 1.0, 'val_accuracy': 0.9219...",2022-11-29 17:41:43.665968,0 days 00:00:06.712829
91,3004001,XGB,amino,kingdom,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 1.0, 'val_accuracy': 0.8644...",2022-11-29 17:41:50.400644,0 days 00:00:04.256763
96,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...","{'train_accuracy': 0.9817405232247731, 'val_ac...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798
97,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...","{'train_accuracy': 0.9750133475707421, 'val_ac...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893
98,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...","{'train_accuracy': 0.7753336892685532, 'val_ac...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428
99,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...","{'train_accuracy': 0.7326214628937533, 'val_ac...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763
100,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...","{'train_accuracy': 0.999359316604378, 'val_acc...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622
101,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...","{'train_accuracy': 0.999786438868126, 'val_acc...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144
102,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...","{'train_accuracy': 0.995835557928457, 'val_acc...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093
103,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...","{'train_accuracy': 0.9864388681260011, 'val_ac...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628
108,5001001,GNB,codon,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9113721302722905, 'val_ac...",2022-11-29 18:32:30.591721,0 days 00:00:00.070126
109,5002001,GNB,amino,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9725573945541911, 'val_ac...",2022-11-29 18:32:30.686872,0 days 00:00:00.030608
110,5003001,GNB,codon,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.5681793913507741, 'val_ac...",2022-11-29 18:32:30.752093,0 days 00:00:00.211462
111,5004001,GNB,amino,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.609930592632141, 'val_acc...",2022-11-29 18:32:30.990350,0 days 00:00:00.149825

Was I stupid enough to label assessment metrics with different names for different trials?  Let's see.

In [233]:
assess = expand_assessment(results)

In [236]:
assess

,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,validation_f1
0,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795,NaN
1,0.997699,0.996968,0.991224,0.995408,0.994555,0.987147,0.99034,0.997256,0.99034,NaN
2,0.99733,0.997579,0.990741,0.997224,0.996975,0.990231,0.990398,0.996975,0.990398,NaN
3,0.996255,0.996668,0.990206,0.994341,0.99516,0.987661,0.990447,0.996067,0.990447,NaN
4,0.996155,0.996368,0.990481,0.996049,0.995765,0.989717,0.990194,0.994878,0.990194,NaN
...,...,...,...,...,...,...,...,...,...,...
95,0.986439,NaN,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,0.856624
96,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018,NaN
97,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265,NaN
98,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453,NaN
99,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576,NaN

Not as bad as I feared; in the future I should be more careful about naming conventions.  Let's fix this.

In [237]:
assess[assess.val_f1.isna()]

,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,validation_f1
88,0.981741,NaN,0.977892,0.981741,0.978221,0.977892,0.998452,0.99831,0.997676,0.978221
89,0.975013,NaN,0.967095,0.975013,0.970357,0.967095,0.986454,0.980197,0.976424,0.970357
90,0.775334,NaN,0.752185,0.775334,0.745312,0.752185,0.951042,0.934508,0.941312,0.745312
91,0.732621,NaN,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607,0.725953
92,0.999359,NaN,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,0.998790
93,0.999786,NaN,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,0.994555
94,0.995836,NaN,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,0.947368
95,0.986439,NaN,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,0.856624

In [238]:
# is there no more elegant way to do this?
assess[assess.val_f1.isna()].val_f1 = assess[assess.val_f1.isna()].validation_f1

In [239]:
assess[assess.val_f1.isna()]

,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,validation_f1
88,0.981741,NaN,0.977892,0.981741,0.978221,0.977892,0.998452,0.99831,0.997676,0.978221
89,0.975013,NaN,0.967095,0.975013,0.970357,0.967095,0.986454,0.980197,0.976424,0.970357
90,0.775334,NaN,0.752185,0.775334,0.745312,0.752185,0.951042,0.934508,0.941312,0.745312
91,0.732621,NaN,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607,0.725953
92,0.999359,NaN,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,0.998790
93,0.999786,NaN,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,0.994555
94,0.995836,NaN,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,0.947368
95,0.986439,NaN,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,0.856624

In [240]:
# apparently that didn't even work.  (WHY?)  The internst suggests to use fillna()

assess.val_f1.fillna(assess.validation_f1, inplace=True)

In [241]:
assess[assess.val_f1.isna()]

Empty DataFrame
Columns: [train_f1, val_f1, test_f1, train_accuracy, val_accuracy, test_accuracy, train_roc_auc, val_roc_auc, test_roc_auc, validation_f1]
Index: []

In [242]:
# and now drop the redundant column
assess = assess.drop('validation_f1', axis=1)

In [243]:
assess

,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
1,0.997699,0.996968,0.991224,0.995408,0.994555,0.987147,0.99034,0.997256,0.99034
2,0.99733,0.997579,0.990741,0.997224,0.996975,0.990231,0.990398,0.996975,0.990398
3,0.996255,0.996668,0.990206,0.994341,0.99516,0.987661,0.990447,0.996067,0.990447
4,0.996155,0.996368,0.990481,0.996049,0.995765,0.989717,0.990194,0.994878,0.990194
...,...,...,...,...,...,...,...,...,...
95,0.986439,0.856624,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279
96,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018
97,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265
98,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453
99,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576

In [250]:
resultsa = pd.merge(results, assess, left_index=True, right_index=True)

In [247]:
resultsa

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1001001,kNN,codon,dna,{'k': 1},"{'train_f1': 1.0, 'val_f1': 0.9981851179673321...",2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
1,1001001,kNN,codon,dna,{'k': 2},"{'train_f1': 0.9976989350885642, 'val_f1': 0.9...",2022-11-29 16:04:16.040980,0 days 00:00:03.790893,0.997699,0.996968,0.991224,0.995408,0.994555,0.987147,0.99034,0.997256,0.99034
2,1001001,kNN,codon,dna,{'k': 3},"{'train_f1': 0.9973302007689021, 'val_f1': 0.9...",2022-11-29 16:04:19.848398,0 days 00:00:03.879642,0.99733,0.997579,0.990741,0.997224,0.996975,0.990231,0.990398,0.996975,0.990398
3,1001001,kNN,codon,dna,{'k': 4},"{'train_f1': 0.9962554830426874, 'val_f1': 0.9...",2022-11-29 16:04:23.743797,0 days 00:00:05.662143,0.996255,0.996668,0.990206,0.994341,0.99516,0.987661,0.990447,0.996067,0.990447
4,1001001,kNN,codon,dna,{'k': 5},"{'train_f1': 0.9961554891072192, 'val_f1': 0.9...",2022-11-29 16:04:29.419867,0 days 00:00:05.053719,0.996155,0.996368,0.990481,0.996049,0.995765,0.989717,0.990194,0.994878,0.990194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,3004001,XGB,amino,kingdom,{'hyperparameters': 'XGBClassifier defaults'},"{'train_accuracy': 1.0, 'val_accuracy': 0.8644...",2022-11-29 17:41:50.400644,0 days 00:00:04.256763,0.732621,0.725953,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607
96,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...","{'train_accuracy': 0.9817405232247731, 'val_ac...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018
97,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...","{'train_accuracy': 0.9750133475707421, 'val_ac...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265
98,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...","{'train_accuracy': 0.7753336892685532, 'val_ac...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453
99,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...","{'train_accuracy': 0.7326214628937533, 'val_ac...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576

In [248]:
# the 'assessment' column is now redundant
resultsa = resultsa.drop('assessment', axis=1)

In [249]:
resultsa

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
1,1001001,kNN,codon,dna,{'k': 2},2022-11-29 16:04:16.040980,0 days 00:00:03.790893,0.997699,0.996968,0.991224,0.995408,0.994555,0.987147,0.99034,0.997256,0.99034
2,1001001,kNN,codon,dna,{'k': 3},2022-11-29 16:04:19.848398,0 days 00:00:03.879642,0.99733,0.997579,0.990741,0.997224,0.996975,0.990231,0.990398,0.996975,0.990398
3,1001001,kNN,codon,dna,{'k': 4},2022-11-29 16:04:23.743797,0 days 00:00:05.662143,0.996255,0.996668,0.990206,0.994341,0.99516,0.987661,0.990447,0.996067,0.990447
4,1001001,kNN,codon,dna,{'k': 5},2022-11-29 16:04:29.419867,0 days 00:00:05.053719,0.996155,0.996368,0.990481,0.996049,0.995765,0.989717,0.990194,0.994878,0.990194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,3004001,XGB,amino,kingdom,{'hyperparameters': 'XGBClassifier defaults'},2022-11-29 17:41:50.400644,0 days 00:00:04.256763,0.732621,0.725953,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607
96,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018
97,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265
98,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453
99,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576

Now I need to identify the best models for the k-NN and RF models, on which I didn't use hyperopt.

In [112]:
# again:  there must be a better way
# using boolean operators failed pretty badly

knn = resultsa[resultsa['model_type'] == 'kNN']
knn_D = knn[knn['outputs'] == 'dna']
knn_D_c = knn_D[knn_D['inputs'] == 'codon']
knn_D_a = knn_D[knn_D['inputs'] == 'amino']
knn_K = knn[knn['outputs'] == 'king']
knn_K_c = knn_K[knn_K['inputs'] == 'codon']
knn_K_a = knn_K[knn_K['inputs'] == 'amino']

In [114]:

rfc = resultsa[resultsa['model_type'] == 'RFC']
rfc_D = rfc[rfc['outputs'] == 'dna']
rfc_D_c = rfc_D[rfc_D['inputs'] == 'codon']
rfc_D_a = rfc_D[rfc_D['inputs'] == 'amino']

In [125]:
rfc_K = rfc[rfc['outputs'] != 'dna']

In [138]:
# For some reason, both of these failed, returning an IndexingErrorL
# Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
#rfc_K_c = rfc[rfc_K['inputs'] == 'codon']
#rfc_K_a = rfc[rfc_K['inputs'] == 'amino']

# I am forced to compose these manually just to get it done, but this is unsatisfying.

rfc_K_c = rfc_K.loc[rfc_K['inputs'] == 'codon']
rfc_K_a = rfc_K.loc[rfc_K['inputs'] == 'amino']

In [139]:
rfc_K_a

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},2022-11-29 16:10:55.333264,0 days 00:00:07.051315,1.0,0.820584,0.820165,1.0,0.713854,0.715167,0.853735,0.853696,0.853735
74,2004001,RFC,amino,kingdom,{'n_estimators': 220},2022-11-29 16:10:55.333264,0 days 00:00:07.068262,1.0,0.823203,0.818879,1.0,0.716878,0.713625,0.852895,0.855373,0.852895
75,2004001,RFC,amino,kingdom,{'n_estimators': 240},2022-11-29 16:10:55.333264,0 days 00:00:07.079240,1.0,0.821975,0.819227,1.0,0.715064,0.714139,0.853151,0.854465,0.853151
76,2004001,RFC,amino,kingdom,{'n_estimators': 260},2022-11-29 16:10:55.333264,0 days 00:00:07.090195,1.0,0.820209,0.817833,1.0,0.712039,0.712082,0.852153,0.853035,0.852153
77,2004001,RFC,amino,kingdom,{'n_estimators': 280},2022-11-29 16:10:55.333264,0 days 00:00:07.102154,1.0,0.820334,0.818531,1.0,0.712644,0.713111,0.852645,0.853256,0.852645
78,2004001,RFC,amino,kingdom,{'n_estimators': 300},2022-11-29 16:10:55.333264,0 days 00:00:07.112124,1.0,0.822261,0.818638,1.0,0.715064,0.713625,0.852845,0.854557,0.852845
79,2004001,RFC,amino,kingdom,{'n_estimators': 320},2022-11-29 16:10:55.333264,0 days 00:00:07.124080,1.0,0.821851,0.816893,1.0,0.714459,0.711054,0.85156,0.854254,0.85156
80,2004001,RFC,amino,kingdom,{'n_estimators': 340},2022-11-29 16:10:55.333264,0 days 00:00:07.134053,1.0,0.820495,0.817591,1.0,0.712039,0.712082,0.852053,0.853127,0.852053
81,2004001,RFC,amino,kingdom,{'n_estimators': 360},2022-11-29 16:10:55.333264,0 days 00:00:07.146007,1.0,0.820495,0.819817,1.0,0.712039,0.714653,0.853473,0.853127,0.853473
82,2004001,RFC,amino,kingdom,{'n_estimators': 380},2022-11-29 16:10:55.333264,0 days 00:00:07.156927,1.0,0.821889,0.819682,1.0,0.713249,0.715167,0.853625,0.853896,0.853625
83,2004001,RFC,amino,kingdom,{'n_estimators': 400},2022-11-29 16:10:55.333264,0 days 00:00:07.167932,1.0,0.820495,0.819227,1.0,0.712039,0.714139,0.853161,0.853151,0.853161

In [140]:
rfc_K_c

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
62,2003001,RFC,codon,kingdom,{'n_estimators': 200},2022-11-29 16:09:54.119362,0 days 00:00:08.705608,1.0,0.850904,0.848238,1.0,0.754386,0.748586,0.872207,0.874959,0.872207
63,2003001,RFC,codon,kingdom,{'n_estimators': 220},2022-11-29 16:09:54.119362,0 days 00:00:08.719576,1.0,0.849539,0.850247,1.0,0.753176,0.751671,0.873757,0.874187,0.873757
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},2022-11-29 16:09:54.119362,0 days 00:00:08.730520,1.0,0.848464,0.851744,1.0,0.751966,0.753213,0.874602,0.873578,0.874602
65,2003001,RFC,codon,kingdom,{'n_estimators': 260},2022-11-29 16:09:54.119362,0 days 00:00:08.742486,1.0,0.848960,0.849315,1.0,0.753176,0.7491,0.872616,0.874117,0.872616
66,2003001,RFC,codon,kingdom,{'n_estimators': 280},2022-11-29 16:09:54.119362,0 days 00:00:08.753403,1.0,0.849829,0.85032,1.0,0.753176,0.750643,0.873387,0.87436,0.873387
67,2003001,RFC,codon,kingdom,{'n_estimators': 300},2022-11-29 16:09:54.119362,0 days 00:00:08.765407,1.0,0.851789,0.851324,1.0,0.756201,0.752185,0.874159,0.875945,0.874159
68,2003001,RFC,codon,kingdom,{'n_estimators': 320},2022-11-29 16:09:54.119362,0 days 00:00:08.776372,1.0,0.849932,0.85141,1.0,0.753781,0.752699,0.874336,0.874657,0.874336
69,2003001,RFC,codon,kingdom,{'n_estimators': 340},2022-11-29 16:09:54.119362,0 days 00:00:08.787339,1.0,0.852861,0.850407,1.0,0.757411,0.751157,0.873559,0.876545,0.873559
70,2003001,RFC,codon,kingdom,{'n_estimators': 360},2022-11-29 16:09:54.119362,0 days 00:00:08.799298,1.0,0.853451,0.85141,1.0,0.759226,0.752699,0.87433,0.877292,0.87433
71,2003001,RFC,codon,kingdom,{'n_estimators': 380},2022-11-29 16:09:54.119362,0 days 00:00:08.810258,1.0,0.853061,0.851497,1.0,0.758621,0.753213,0.874517,0.876989,0.874517
72,2003001,RFC,codon,kingdom,{'n_estimators': 400},2022-11-29 16:09:54.119362,0 days 00:00:08.821226,1.0,0.852481,0.851076,1.0,0.758621,0.752185,0.874073,0.876907,0.874073

In [142]:
best_models

Empty DataFrame
Columns: [model_type, inputs, outputs, hyperparameters, test_f1, test_accuracy, test_roc_auc, runtime]
Index: []

In [158]:
# find the 'best' model from a results dataframe based on max criterion
# CAN return multiple rows

def find_best(df, by='test_f1'):
    best = df.loc[df[by] == df[by].max()]
    return best

In [152]:
find_best(knn_K_c)

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
22,1003001,kNN,codon,king,{'k': 3},2022-11-29 16:05:55.838435,0 days 00:00:05.072418,0.963178,0.918573,0.938426,0.956647,0.911071,0.928535,0.959277,0.949136,0.959277

In [157]:
find_best(rfc_D_c)

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
42,2001001,RFC,codon,dna,{'n_estimators': 240},2022-11-29 16:08:24.053694,0 days 00:00:03.250867,0.999893,0.988178,0.989175,0.999893,0.986086,0.986632,0.984949,0.981899,0.984949

This seems to work great!  Now, I need to put these 'best' models into a dataframe.

In [165]:
df_list = [knn_D_c, knn_D_a, knn_K_c, knn_K_a, rfc_D_c, rfc_D_a, rfc_K_c, rfc_K_a]

In [166]:
rawbest = pd.DataFrame(columns=knn.columns)

In [169]:
for df in df_list:
    rawbest = rawbest.append(find_best(df))

In [171]:
rawbest

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
10,1002001,kNN,amino,dna,{'k': 1},2022-11-29 16:04:59.951773,0 days 00:00:03.408583,0.999893,0.99395,0.989203,0.999893,0.99395,0.989203,0.98736,0.992949,0.98736
22,1003001,kNN,codon,king,{'k': 3},2022-11-29 16:05:55.838435,0 days 00:00:05.072418,0.963178,0.918573,0.938426,0.956647,0.911071,0.928535,0.959277,0.949136,0.959277
32,1004001,kNN,amino,king,{'k': 3},2022-11-29 16:06:54.762894,0 days 00:00:05.091228,0.92797,0.857409,0.869588,0.911372,0.836661,0.846787,0.912353,0.906811,0.912353
42,2001001,RFC,codon,dna,{'n_estimators': 240},2022-11-29 16:08:24.053694,0 days 00:00:03.250867,0.999893,0.988178,0.989175,0.999893,0.986086,0.986632,0.984949,0.981899,0.984949
57,2002001,RFC,amino,dna,{'n_estimators': 320},2022-11-29 16:08:46.856963,0 days 00:00:02.900102,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
58,2002001,RFC,amino,dna,{'n_estimators': 340},2022-11-29 16:08:46.856963,0 days 00:00:02.911078,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
59,2002001,RFC,amino,dna,{'n_estimators': 360},2022-11-29 16:08:46.856963,0 days 00:00:02.925031,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},2022-11-29 16:09:54.119362,0 days 00:00:08.730520,1.0,0.848464,0.851744,1.0,0.751966,0.753213,0.874602,0.873578,0.874602
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},2022-11-29 16:10:55.333264,0 days 00:00:07.051315,1.0,0.820584,0.820165,1.0,0.713854,0.715167,0.853735,0.853696,0.853735

In [172]:
# let's compare with the lists based on accuracy and roc_auc...
rawbest_acc = pd.DataFrame(columns=knn.columns)
rawbest_auc = pd.DataFrame(columns=knn.columns)

for df in df_list:
    rawbest_acc = rawbest_acc.append(find_best(df, by='test_accuracy'))
    rawbest_auc = rawbest_auc.append(find_best(df, by='test_roc_auc'))

In [173]:
rawbest_acc

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
10,1002001,kNN,amino,dna,{'k': 1},2022-11-29 16:04:59.951773,0 days 00:00:03.408583,0.999893,0.99395,0.989203,0.999893,0.99395,0.989203,0.98736,0.992949,0.98736
20,1003001,kNN,codon,king,{'k': 1},2022-11-29 16:05:46.350600,0 days 00:00:04.571322,1.0,0.936479,0.932134,1.0,0.936479,0.932134,0.96003,0.963154,0.96003
30,1004001,kNN,amino,king,{'k': 1},2022-11-29 16:06:45.454885,0 days 00:00:04.478091,1.0,0.851785,0.862725,1.0,0.851785,0.862725,0.917839,0.911643,0.917839
42,2001001,RFC,codon,dna,{'n_estimators': 240},2022-11-29 16:08:24.053694,0 days 00:00:03.250867,0.999893,0.988178,0.989175,0.999893,0.986086,0.986632,0.984949,0.981899,0.984949
57,2002001,RFC,amino,dna,{'n_estimators': 320},2022-11-29 16:08:46.856963,0 days 00:00:02.900102,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
58,2002001,RFC,amino,dna,{'n_estimators': 340},2022-11-29 16:08:46.856963,0 days 00:00:02.911078,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
59,2002001,RFC,amino,dna,{'n_estimators': 360},2022-11-29 16:08:46.856963,0 days 00:00:02.925031,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},2022-11-29 16:09:54.119362,0 days 00:00:08.730520,1.0,0.848464,0.851744,1.0,0.751966,0.753213,0.874602,0.873578,0.874602
71,2003001,RFC,codon,kingdom,{'n_estimators': 380},2022-11-29 16:09:54.119362,0 days 00:00:08.810258,1.0,0.853061,0.851497,1.0,0.758621,0.753213,0.874517,0.876989,0.874517
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},2022-11-29 16:10:55.333264,0 days 00:00:07.051315,1.0,0.820584,0.820165,1.0,0.713854,0.715167,0.853735,0.853696,0.853735
82,2004001,RFC,amino,kingdom,{'n_estimators': 380},2022-11-29 16:10:55.333264,0 days 00:00:07.156927,1.0,0.821889,0.819682,1.0,0.713249,0.715167,0.853625,0.853896,0.853625

In [174]:
rawbest_auc

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
12,1002001,kNN,amino,dna,{'k': 3},2022-11-29 16:05:07.119415,0 days 00:00:03.754226,0.995461,0.994555,0.988937,0.995302,0.994555,0.988175,0.987372,0.992382,0.987372
20,1003001,kNN,codon,king,{'k': 1},2022-11-29 16:05:46.350600,0 days 00:00:04.571322,1.0,0.936479,0.932134,1.0,0.936479,0.932134,0.96003,0.963154,0.96003
30,1004001,kNN,amino,king,{'k': 1},2022-11-29 16:06:45.454885,0 days 00:00:04.478091,1.0,0.851785,0.862725,1.0,0.851785,0.862725,0.917839,0.911643,0.917839
42,2001001,RFC,codon,dna,{'n_estimators': 240},2022-11-29 16:08:24.053694,0 days 00:00:03.250867,0.999893,0.988178,0.989175,0.999893,0.986086,0.986632,0.984949,0.981899,0.984949
54,2002001,RFC,amino,dna,{'n_estimators': 260},2022-11-29 16:08:46.856963,0 days 00:00:02.863242,1.0,0.98758,0.983996,1.0,0.986086,0.979949,0.97602,0.981461,0.97602
60,2002001,RFC,amino,dna,{'n_estimators': 380},2022-11-29 16:08:46.856963,0 days 00:00:02.938004,1.0,0.986667,0.983996,1.0,0.984876,0.979949,0.97602,0.980088,0.97602
61,2002001,RFC,amino,dna,{'n_estimators': 400},2022-11-29 16:08:46.856963,0 days 00:00:02.949945,1.0,0.986667,0.983996,1.0,0.984876,0.979949,0.97602,0.980088,0.97602
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},2022-11-29 16:09:54.119362,0 days 00:00:08.730520,1.0,0.848464,0.851744,1.0,0.751966,0.753213,0.874602,0.873578,0.874602
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},2022-11-29 16:10:55.333264,0 days 00:00:07.051315,1.0,0.820584,0.820165,1.0,0.713854,0.715167,0.853735,0.853696,0.853735

The results don't match exactly - they shouldn't be expected to.  I'm going to proceed using micro F1, as that's what hyperopt used and I want to be consistent.  Now I can simply append the rows for the models where hyperopt was used.

In [178]:
xgb = resultsa[resultsa['model_type'].str.contains('XGB')]

In [179]:
xgb

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
88,3001001,XGB,codon,dna,{'hyperparameters': 'XGBClassifier defaults'},2022-11-29 17:41:41.378498,0 days 00:00:01.378242,0.981741,0.978221,0.977892,0.981741,0.978221,0.977892,0.998452,0.99831,0.997676
89,3002001,XGB,amino,dna,{'hyperparameters': 'XGBClassifier defaults'},2022-11-29 17:41:42.784433,0 days 00:00:00.846796,0.975013,0.970357,0.967095,0.975013,0.970357,0.967095,0.986454,0.980197,0.976424
90,3003001,XGB,codon,kingdom,{'hyperparameters': 'XGBClassifier defaults'},2022-11-29 17:41:43.665968,0 days 00:00:06.712829,0.775334,0.745312,0.752185,0.775334,0.745312,0.752185,0.951042,0.934508,0.941312
91,3004001,XGB,amino,kingdom,{'hyperparameters': 'XGBClassifier defaults'},2022-11-29 17:41:50.400644,0 days 00:00:04.256763,0.732621,0.725953,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607
96,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018
97,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265
98,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453
99,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576

In [180]:
xgb.loc[96]['hyperparameters']

{'colsample_bytree': 0.6110138615418974,
 'gamma': 1.009256576029583,
 'max_depth': 7.0,
 'min_child_weight': 7.0,
 'reg_alpha': 41.0,
 'reg_lambda': 0.7271760162194361}

In [294]:
def expand_hp(df):
    hp = df.hyperparameters
    new_df = pd.DataFrame(columns = hp[0].keys())
    for param in hp:
        new_df = new_df.append(param, ignore_index=True)
    return new_df

In [198]:
xgb_defaults = {'colsample_bytree': 1,
 'gamma': 0,
 'max_depth': 3,
 'min_child_weight': 1,
 'reg_alpha': 0,
 'reg_lambda': 1}

In [199]:
xgb.hyperparameters[88]

{'colsample_bytree': 1,
 'gamma': 0,
 'max_depth': 3,
 'min_child_weight': 1,
 'reg_alpha': 0,
 'reg_lambda': 1}

In [200]:
xgb.hyperparameters[91] = xgb_defaults

In [201]:
xgb

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
88,3001001,XGB,codon,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:41.378498,0 days 00:00:01.378242,0.981741,0.978221,0.977892,0.981741,0.978221,0.977892,0.998452,0.99831,0.997676
89,3002001,XGB,amino,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:42.784433,0 days 00:00:00.846796,0.975013,0.970357,0.967095,0.975013,0.970357,0.967095,0.986454,0.980197,0.976424
90,3003001,XGB,codon,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:43.665968,0 days 00:00:06.712829,0.775334,0.745312,0.752185,0.775334,0.745312,0.752185,0.951042,0.934508,0.941312
91,3004001,XGB,amino,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:50.400644,0 days 00:00:04.256763,0.732621,0.725953,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607
96,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018
97,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265
98,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453
99,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576

In [202]:
hypers = expand_hp(xgb)

In [203]:
hypers

  colsample_bytree     gamma max_depth min_child_weight reg_alpha reg_lambda
0                1         0         3                1         0          1
1                1         0         3                1         0          1
2                1         0         3                1         0          1
3                1         0         3                1         0          1
4         0.611014  1.009257       7.0              7.0      41.0   0.727176
5          0.75504  1.003959      11.0              3.0      50.0   0.536313
6         0.887277  1.027571      16.0             10.0      40.0   0.490005
7         0.645089  1.642394       5.0              4.0      40.0   0.410833

In [209]:
xgb.reset_index(inplace=True)

In [211]:

xgba = pd.merge(xgb, hypers, left_index=True, right_index=True)

In [212]:
xgba

,index,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,...,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,colsample_bytree,gamma,max_depth,min_child_weight,reg_alpha,reg_lambda
0,88,3001001,XGB,codon,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:41.378498,0 days 00:00:01.378242,0.981741,0.978221,...,0.977892,0.998452,0.99831,0.997676,1,0,3,1,0,1
1,89,3002001,XGB,amino,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:42.784433,0 days 00:00:00.846796,0.975013,0.970357,...,0.967095,0.986454,0.980197,0.976424,1,0,3,1,0,1
2,90,3003001,XGB,codon,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:43.665968,0 days 00:00:06.712829,0.775334,0.745312,...,0.752185,0.951042,0.934508,0.941312,1,0,3,1,0,1
3,91,3004001,XGB,amino,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:50.400644,0 days 00:00:04.256763,0.732621,0.725953,...,0.720823,0.929769,0.90904,0.915607,1,0,3,1,0,1
4,96,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798,0.911372,0.910466,...,0.906941,0.990913,0.991436,0.990018,0.611014,1.009257,7.0,7.0,41.0,0.727176
5,97,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893,0.972557,0.974592,...,0.966067,0.981676,0.985361,0.975265,0.75504,1.003959,11.0,3.0,50.0,0.536313
6,98,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428,0.568179,0.580157,...,0.580977,0.912869,0.906309,0.91453,0.887277,1.027571,16.0,10.0,40.0,0.490005
7,99,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763,0.609931,0.606776,...,0.615938,0.892769,0.882913,0.888576,0.645089,1.642394,5.0,4.0,40.0,0.410833

In [213]:
rawbest

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
10,1002001,kNN,amino,dna,{'k': 1},2022-11-29 16:04:59.951773,0 days 00:00:03.408583,0.999893,0.99395,0.989203,0.999893,0.99395,0.989203,0.98736,0.992949,0.98736
22,1003001,kNN,codon,king,{'k': 3},2022-11-29 16:05:55.838435,0 days 00:00:05.072418,0.963178,0.918573,0.938426,0.956647,0.911071,0.928535,0.959277,0.949136,0.959277
32,1004001,kNN,amino,king,{'k': 3},2022-11-29 16:06:54.762894,0 days 00:00:05.091228,0.92797,0.857409,0.869588,0.911372,0.836661,0.846787,0.912353,0.906811,0.912353
42,2001001,RFC,codon,dna,{'n_estimators': 240},2022-11-29 16:08:24.053694,0 days 00:00:03.250867,0.999893,0.988178,0.989175,0.999893,0.986086,0.986632,0.984949,0.981899,0.984949
57,2002001,RFC,amino,dna,{'n_estimators': 320},2022-11-29 16:08:46.856963,0 days 00:00:02.900102,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
58,2002001,RFC,amino,dna,{'n_estimators': 340},2022-11-29 16:08:46.856963,0 days 00:00:02.911078,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
59,2002001,RFC,amino,dna,{'n_estimators': 360},2022-11-29 16:08:46.856963,0 days 00:00:02.925031,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},2022-11-29 16:09:54.119362,0 days 00:00:08.730520,1.0,0.848464,0.851744,1.0,0.751966,0.753213,0.874602,0.873578,0.874602
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},2022-11-29 16:10:55.333264,0 days 00:00:07.051315,1.0,0.820584,0.820165,1.0,0.713854,0.715167,0.853735,0.853696,0.853735

In [214]:
rawbest = rawbest.append(xgb)

In [215]:
rawbest

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,index
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795,NaN
10,1002001,kNN,amino,dna,{'k': 1},2022-11-29 16:04:59.951773,0 days 00:00:03.408583,0.999893,0.99395,0.989203,0.999893,0.99395,0.989203,0.98736,0.992949,0.98736,NaN
22,1003001,kNN,codon,king,{'k': 3},2022-11-29 16:05:55.838435,0 days 00:00:05.072418,0.963178,0.918573,0.938426,0.956647,0.911071,0.928535,0.959277,0.949136,0.959277,NaN
32,1004001,kNN,amino,king,{'k': 3},2022-11-29 16:06:54.762894,0 days 00:00:05.091228,0.92797,0.857409,0.869588,0.911372,0.836661,0.846787,0.912353,0.906811,0.912353,NaN
42,2001001,RFC,codon,dna,{'n_estimators': 240},2022-11-29 16:08:24.053694,0 days 00:00:03.250867,0.999893,0.988178,0.989175,0.999893,0.986086,0.986632,0.984949,0.981899,0.984949,NaN
57,2002001,RFC,amino,dna,{'n_estimators': 320},2022-11-29 16:08:46.856963,0 days 00:00:02.900102,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646,NaN
58,2002001,RFC,amino,dna,{'n_estimators': 340},2022-11-29 16:08:46.856963,0 days 00:00:02.911078,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646,NaN
59,2002001,RFC,amino,dna,{'n_estimators': 360},2022-11-29 16:08:46.856963,0 days 00:00:02.925031,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646,NaN
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},2022-11-29 16:09:54.119362,0 days 00:00:08.730520,1.0,0.848464,0.851744,1.0,0.751966,0.753213,0.874602,0.873578,0.874602,NaN
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},2022-11-29 16:10:55.333264,0 days 00:00:07.051315,1.0,0.820584,0.820165,1.0,0.713854,0.715167,0.853735,0.853696,0.853735,NaN
0,3001001,XGB,codon,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:41.378498,0 days 00:00:01.378242,0.981741,0.978221,0.977892,0.981741,0.978221,0.977892,0.998452,0.99831,0.997676,88.0
1,3002001,XGB,amino,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:42.784433,0 days 00:00:00.846796,0.975013,0.970357,0.967095,0.975013,0.970357,0.967095,0.986454,0.980197,0.976424,89.0
2,3003001,XGB,codon,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:43.665968,0 days 00:00:06.712829,0.775334,0.745312,0.752185,0.775334,0.745312,0.752185,0.951042,0.934508,0.941312,90.0
3,3004001,XGB,amino,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:50.400644,0 days 00:00:04.256763,0.732621,0.725953,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607,91.0
4,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018,96.0
5,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265,97.0
6,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453,98.0
7,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576,99.0

In [216]:
resultsa.shape

(92, 16)

In [224]:
resultsa[:-10]

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795
1,1001001,kNN,codon,dna,{'k': 2},2022-11-29 16:04:16.040980,0 days 00:00:03.790893,0.997699,0.996968,0.991224,0.995408,0.994555,0.987147,0.99034,0.997256,0.99034
2,1001001,kNN,codon,dna,{'k': 3},2022-11-29 16:04:19.848398,0 days 00:00:03.879642,0.99733,0.997579,0.990741,0.997224,0.996975,0.990231,0.990398,0.996975,0.990398
3,1001001,kNN,codon,dna,{'k': 4},2022-11-29 16:04:23.743797,0 days 00:00:05.662143,0.996255,0.996668,0.990206,0.994341,0.99516,0.987661,0.990447,0.996067,0.990447
4,1001001,kNN,codon,dna,{'k': 5},2022-11-29 16:04:29.419867,0 days 00:00:05.053719,0.996155,0.996368,0.990481,0.996049,0.995765,0.989717,0.990194,0.994878,0.990194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2004001,RFC,amino,kingdom,{'n_estimators': 280},2022-11-29 16:10:55.333264,0 days 00:00:07.102154,1.0,0.820334,0.818531,1.0,0.712644,0.713111,0.852645,0.853256,0.852645
78,2004001,RFC,amino,kingdom,{'n_estimators': 300},2022-11-29 16:10:55.333264,0 days 00:00:07.112124,1.0,0.822261,0.818638,1.0,0.715064,0.713625,0.852845,0.854557,0.852845
79,2004001,RFC,amino,kingdom,{'n_estimators': 320},2022-11-29 16:10:55.333264,0 days 00:00:07.124080,1.0,0.821851,0.816893,1.0,0.714459,0.711054,0.85156,0.854254,0.85156
80,2004001,RFC,amino,kingdom,{'n_estimators': 340},2022-11-29 16:10:55.333264,0 days 00:00:07.134053,1.0,0.820495,0.817591,1.0,0.712039,0.712082,0.852053,0.853127,0.852053
81,2004001,RFC,amino,kingdom,{'n_estimators': 360},2022-11-29 16:10:55.333264,0 days 00:00:07.146007,1.0,0.820495,0.819817,1.0,0.712039,0.714653,0.853473,0.853127,0.853473

In [253]:
# oddly, these got stripped from resultsa
#mlp = resultsa[resultsa['model_type'].str.contains('MLP')]
#gnb = resultsa[resultsa['model_type'].str.contains('GNB')]

mlp = results[results['model_type'].str.contains('MLP')]
gnb = results[results['model_type'].str.contains('GNB')]

In [254]:
mlp

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
100,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...","{'train_accuracy': 0.999359316604378, 'val_acc...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622
101,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...","{'train_accuracy': 0.999786438868126, 'val_acc...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144
102,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...","{'train_accuracy': 0.995835557928457, 'val_acc...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093
103,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...","{'train_accuracy': 0.9864388681260011, 'val_ac...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628

In [255]:
gnb

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
108,5001001,GNB,codon,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9113721302722905, 'val_ac...",2022-11-29 18:32:30.591721,0 days 00:00:00.070126
109,5002001,GNB,amino,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9725573945541911, 'val_ac...",2022-11-29 18:32:30.686872,0 days 00:00:00.030608
110,5003001,GNB,codon,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.5681793913507741, 'val_ac...",2022-11-29 18:32:30.752093,0 days 00:00:00.211462
111,5004001,GNB,amino,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.609930592632141, 'val_acc...",2022-11-29 18:32:30.990350,0 days 00:00:00.149825

In [258]:
both = pd.concat([mlp, gnb])

In [259]:
both

,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
100,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...","{'train_accuracy': 0.999359316604378, 'val_acc...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622
101,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...","{'train_accuracy': 0.999786438868126, 'val_acc...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144
102,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...","{'train_accuracy': 0.995835557928457, 'val_acc...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093
103,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...","{'train_accuracy': 0.9864388681260011, 'val_ac...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628
108,5001001,GNB,codon,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9113721302722905, 'val_ac...",2022-11-29 18:32:30.591721,0 days 00:00:00.070126
109,5002001,GNB,amino,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9725573945541911, 'val_ac...",2022-11-29 18:32:30.686872,0 days 00:00:00.030608
110,5003001,GNB,codon,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.5681793913507741, 'val_ac...",2022-11-29 18:32:30.752093,0 days 00:00:00.211462
111,5004001,GNB,amino,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.609930592632141, 'val_acc...",2022-11-29 18:32:30.990350,0 days 00:00:00.149825

In [262]:
both.reset_index(inplace=True)
bass = expand_assessment(both)

In [263]:
bass

,train_accuracy,val_accuracy,test_accuracy,train_f1,validation_f1,test_f1,train_roc_auc,val_roc_auc,test_roc_auc,val_f1
0,0.999359,0.99879,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,NaN
1,0.999786,0.994555,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,NaN
2,0.995836,0.947368,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,NaN
3,0.986439,0.856624,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,NaN
4,0.911372,0.910466,0.906941,0.911372,NaN,0.906941,0.990913,0.991436,0.990018,0.910466
5,0.972557,0.974592,0.966067,0.972557,NaN,0.966067,0.981676,0.985361,0.975265,0.974592
6,0.568179,0.580157,0.580977,0.568179,NaN,0.580977,0.912869,0.906309,0.91453,0.580157
7,0.609931,0.606776,0.615938,0.609931,NaN,0.615938,0.892769,0.882913,0.888576,0.606776

In [264]:
# same stupid problem as before, use naming conventions 
bass.val_f1.fillna(bass.validation_f1, inplace=True)
bass

,train_accuracy,val_accuracy,test_accuracy,train_f1,validation_f1,test_f1,train_roc_auc,val_roc_auc,test_roc_auc,val_f1
0,0.999359,0.99879,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,0.998790
1,0.999786,0.994555,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,0.994555
2,0.995836,0.947368,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,0.947368
3,0.986439,0.856624,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,0.856624
4,0.911372,0.910466,0.906941,0.911372,NaN,0.906941,0.990913,0.991436,0.990018,0.910466
5,0.972557,0.974592,0.966067,0.972557,NaN,0.966067,0.981676,0.985361,0.975265,0.974592
6,0.568179,0.580157,0.580977,0.568179,NaN,0.580977,0.912869,0.906309,0.91453,0.580157
7,0.609931,0.606776,0.615938,0.609931,NaN,0.615938,0.892769,0.882913,0.888576,0.606776

In [267]:
bass.drop('validation_f1', axis=1, inplace=True)

In [269]:
both

,index,model_id,model_type,inputs,outputs,hyperparameters,assessment,start_time,run_time
0,100,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...","{'train_accuracy': 0.999359316604378, 'val_acc...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622
1,101,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...","{'train_accuracy': 0.999786438868126, 'val_acc...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144
2,102,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...","{'train_accuracy': 0.995835557928457, 'val_acc...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093
3,103,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...","{'train_accuracy': 0.9864388681260011, 'val_ac...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628
4,108,5001001,GNB,codon,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9113721302722905, 'val_ac...",2022-11-29 18:32:30.591721,0 days 00:00:00.070126
5,109,5002001,GNB,amino,dna,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.9725573945541911, 'val_ac...",2022-11-29 18:32:30.686872,0 days 00:00:00.030608
6,110,5003001,GNB,codon,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.5681793913507741, 'val_ac...",2022-11-29 18:32:30.752093,0 days 00:00:00.211462
7,111,5004001,GNB,amino,kingdom,{'hyperparameters': 'GaussianNB defaults'},"{'train_accuracy': 0.609930592632141, 'val_acc...",2022-11-29 18:32:30.990350,0 days 00:00:00.149825

In [270]:
both2 = pd.merge(both, bass, left_index=True, right_index=True)

In [271]:
both2.drop('assessment', axis=1, inplace=True)

In [272]:
both2

,index,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_accuracy,val_accuracy,test_accuracy,train_f1,test_f1,train_roc_auc,val_roc_auc,test_roc_auc,val_f1
0,100,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622,0.999359,0.99879,0.993316,0.999359,0.993316,0.999999,0.999695,0.999204,0.998790
1,101,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144,0.999786,0.994555,0.991774,0.999786,0.991774,0.999997,0.999657,0.997929,0.994555
2,102,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093,0.995836,0.947368,0.932134,0.995836,0.932134,0.999913,0.993842,0.994854,0.947368
3,103,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628,0.986439,0.856624,0.841645,0.986439,0.841645,0.999712,0.975503,0.974279,0.856624
4,108,5001001,GNB,codon,dna,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.591721,0 days 00:00:00.070126,0.911372,0.910466,0.906941,0.911372,0.906941,0.990913,0.991436,0.990018,0.910466
5,109,5002001,GNB,amino,dna,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.686872,0 days 00:00:00.030608,0.972557,0.974592,0.966067,0.972557,0.966067,0.981676,0.985361,0.975265,0.974592
6,110,5003001,GNB,codon,kingdom,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.752093,0 days 00:00:00.211462,0.568179,0.580157,0.580977,0.568179,0.580977,0.912869,0.906309,0.91453,0.580157
7,111,5004001,GNB,amino,kingdom,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.990350,0 days 00:00:00.149825,0.609931,0.606776,0.615938,0.609931,0.615938,0.892769,0.882913,0.888576,0.606776

In [273]:
rawbest = rawbest.append(both2)

In [274]:
rawbest

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,index
0,1001001,kNN,codon,dna,{'k': 1},2022-11-29 16:04:12.097193,0 days 00:00:03.480415,1.0,0.998185,0.992802,1.0,0.998185,0.992802,0.991795,0.999028,0.991795,NaN
10,1002001,kNN,amino,dna,{'k': 1},2022-11-29 16:04:59.951773,0 days 00:00:03.408583,0.999893,0.99395,0.989203,0.999893,0.99395,0.989203,0.98736,0.992949,0.98736,NaN
22,1003001,kNN,codon,king,{'k': 3},2022-11-29 16:05:55.838435,0 days 00:00:05.072418,0.963178,0.918573,0.938426,0.956647,0.911071,0.928535,0.959277,0.949136,0.959277,NaN
32,1004001,kNN,amino,king,{'k': 3},2022-11-29 16:06:54.762894,0 days 00:00:05.091228,0.92797,0.857409,0.869588,0.911372,0.836661,0.846787,0.912353,0.906811,0.912353,NaN
42,2001001,RFC,codon,dna,{'n_estimators': 240},2022-11-29 16:08:24.053694,0 days 00:00:03.250867,0.999893,0.988178,0.989175,0.999893,0.986086,0.986632,0.984949,0.981899,0.984949,NaN
57,2002001,RFC,amino,dna,{'n_estimators': 320},2022-11-29 16:08:46.856963,0 days 00:00:02.900102,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646,NaN
58,2002001,RFC,amino,dna,{'n_estimators': 340},2022-11-29 16:08:46.856963,0 days 00:00:02.911078,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646,NaN
59,2002001,RFC,amino,dna,{'n_estimators': 360},2022-11-29 16:08:46.856963,0 days 00:00:02.925031,1.0,0.986667,0.984004,1.0,0.984876,0.980463,0.975646,0.980088,0.975646,NaN
64,2003001,RFC,codon,kingdom,{'n_estimators': 240},2022-11-29 16:09:54.119362,0 days 00:00:08.730520,1.0,0.848464,0.851744,1.0,0.751966,0.753213,0.874602,0.873578,0.874602,NaN
73,2004001,RFC,amino,kingdom,{'n_estimators': 200},2022-11-29 16:10:55.333264,0 days 00:00:07.051315,1.0,0.820584,0.820165,1.0,0.713854,0.715167,0.853735,0.853696,0.853735,NaN
0,3001001,XGB,codon,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:41.378498,0 days 00:00:01.378242,0.981741,0.978221,0.977892,0.981741,0.978221,0.977892,0.998452,0.99831,0.997676,88.0
1,3002001,XGB,amino,dna,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:42.784433,0 days 00:00:00.846796,0.975013,0.970357,0.967095,0.975013,0.970357,0.967095,0.986454,0.980197,0.976424,89.0
2,3003001,XGB,codon,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:43.665968,0 days 00:00:06.712829,0.775334,0.745312,0.752185,0.775334,0.745312,0.752185,0.951042,0.934508,0.941312,90.0
3,3004001,XGB,amino,kingdom,"{'colsample_bytree': 1, 'gamma': 0, 'max_depth...",2022-11-29 17:41:50.400644,0 days 00:00:04.256763,0.732621,0.725953,0.720823,0.732621,0.725953,0.720823,0.929769,0.90904,0.915607,91.0
4,3101001,XGB-Hyperopt,codon,dna,"{'colsample_bytree': 0.6110138615418974, 'gamm...",2022-11-29 17:42:18.219650,0 days 00:00:48.336798,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018,96.0
5,3102001,XGB-Hyperopt,amino,dna,"{'colsample_bytree': 0.7550396517385796, 'gamm...",2022-11-29 17:43:06.606859,0 days 00:00:23.287893,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265,97.0
6,3103001,XGB-Hyperopt,codon,kingdom,"{'colsample_bytree': 0.8872769169090322, 'gamm...",2022-11-29 17:43:29.936291,0 days 00:02:41.087428,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453,98.0
7,3104001,XGB-Hyperopt,amino,kingdom,"{'colsample_bytree': 0.6450886315542056, 'gamm...",2022-11-29 17:46:11.061521,0 days 00:02:41.495763,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576,99.0
0,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622,0.999359,0.99879,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,100.0
1,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144,0.999786,0.994555,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,101.0
2,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093,0.995836,0.947368,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,102.0
3,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628,0.986439,0.856624,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,103.0
4,5001001,GNB,codon,dna,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.591721,0 days 00:00:00.070126,0.911372,0.910466,0.906941,0.911372,0.910466,0.906941,0.990913,0.991436,0.990018,108.0
5,5002001,GNB,amino,dna,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.686872,0 days 00:00:00.030608,0.972557,0.974592,0.966067,0.972557,0.974592,0.966067,0.981676,0.985361,0.975265,109.0
6,5003001,GNB,codon,kingdom,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.752093,0 days 00:00:00.211462,0.568179,0.580157,0.580977,0.568179,0.580157,0.580977,0.912869,0.906309,0.91453,110.0
7,5004001,GNB,amino,kingdom,{'hyperparameters': 'GaussianNB defaults'},2022-11-29 18:32:30.990350,0 days 00:00:00.149825,0.609931,0.606776,0.615938,0.609931,0.606776,0.615938,0.892769,0.882913,0.888576,111.0

In [275]:
rawbest.reset_index(inplace=True)

In [276]:
rawbest.to_csv('rawbest.csv', index=False)

In [281]:
mlp = rawbest[rawbest['model_type'] == 'MLP-Hyperopt']

In [282]:
mlp

,level_0,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,index
18,0,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622,0.999359,0.99879,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,100.0
19,1,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144,0.999786,0.994555,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,101.0
20,2,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093,0.995836,0.947368,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,102.0
21,3,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628,0.986439,0.856624,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,103.0

In [287]:
mlp = mlp.drop('level_0', axis=1)

In [289]:
mlp = mlp.reset_index()

In [291]:
mlp = mlp.drop('level_0', axis=1)

In [292]:
mlp

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,index
0,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622,0.999359,0.99879,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,100.0
1,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144,0.999786,0.994555,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,101.0
2,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093,0.995836,0.947368,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,102.0
3,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628,0.986439,0.856624,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,103.0

In [295]:
mlp_h = expand_hp(mlp)

In [296]:
mlp_h

  activation hidden_layer_sizes learning_rate_init
0        0.0              121.0           0.000739
1        1.0               88.0           0.008937
2        0.0               92.0           0.000439
3        2.0              144.0           0.004685

In [297]:
mlpraw = pd.merge(mlp, mlp_h, right_index=True, left_index=True)

In [298]:
mlpraw

,model_id,model_type,inputs,outputs,hyperparameters,start_time,run_time,train_f1,val_f1,test_f1,train_accuracy,val_accuracy,test_accuracy,train_roc_auc,val_roc_auc,test_roc_auc,index,activation,hidden_layer_sizes,learning_rate_init
0,4101001,MLP-Hyperopt,codon,dna,"{'activation': 0, 'hidden_layer_sizes': 121.0,...",2022-11-29 17:48:53.012980,0 days 00:04:38.313622,0.999359,0.99879,0.993316,0.999359,0.99879,0.993316,0.999999,0.999695,0.999204,100.0,0.0,121.0,0.000739
1,4102001,MLP-Hyperopt,amino,dna,"{'activation': 1, 'hidden_layer_sizes': 88.0, ...",2022-11-29 17:53:31.357345,0 days 00:05:57.445144,0.999786,0.994555,0.991774,0.999786,0.994555,0.991774,0.999997,0.999657,0.997929,101.0,1.0,88.0,0.008937
2,4103001,MLP-Hyperopt,codon,kingdom,"{'activation': 0, 'hidden_layer_sizes': 92.0, ...",2022-11-29 17:59:28.835596,0 days 00:09:27.743093,0.995836,0.947368,0.932134,0.995836,0.947368,0.932134,0.999913,0.993842,0.994854,102.0,0.0,92.0,0.000439
3,4104001,MLP-Hyperopt,amino,kingdom,"{'activation': 2, 'hidden_layer_sizes': 144.0,...",2022-11-29 18:08:56.609335,0 days 00:11:19.363628,0.986439,0.856624,0.841645,0.986439,0.856624,0.841645,0.999712,0.975503,0.974279,103.0,2.0,144.0,0.004685

In [300]:
mlpraw = mlpraw.drop('hyperparameters', axis=1)

In [301]:
mlpraw.to_csv('mlpraw.csv', index=False)